name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn pytest flake8

    - name: Run Linting
      run: flake8 train.py

    - name: Run Tests
      run: pytest tests/

