name: MLOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linting
      run: flake8 train.py

    - name: Run Tests
      run: pytest tests/ --import-mode=importlib  # Forces pytest to use correct import

    - name: Train model
      run: |
        python animal_classification_model/animal_classification.py

    - name: Save model
      run: |
        mkdir model
        cp animal_classification_model/animal_classification_model.joblib model/

